name: rhythmtrack_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Habit feature dependencies
  flutter_riverpod: ^2.3.10
  sqflite: ^2.2.8+3
  path: ^1.8.4

  # Screen Time feature dependencies
  app_settings: ^5.1.1

  # UI dependencies
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Habit & dev tools
  riverpod: ^2.3.8
  sqflite_common_ffi: ^2.3.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  